learner         :       DERPP 
optim           :       AdamW
learning_rate   :       0.0005
momentum        :       0.9
weight_decay    :       0.0001
dataset         :       tiny
img_size        :       64
dim_in          :       2048
n_classes       :       200
n_tasks         :       100
mem_size        :       2000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
training_type   :       inc
seed            :       0
derpp_alpha     :       0.2
derpp_beta      :       1.0
tf_type         :       partial