learner         :       ERACECCLDC
optim           :       AdamW
learning_rate   :       0.0005
momentum        :       0
weight_decay    :       0.0001
dataset         :       tiny
img_size        :       64
dim_in          :       2048
n_classes       :       200
n_tasks         :       100
mem_size        :       10000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
tf_type         :       partial 
training_type   :       inc
seed            :       0
randaug_m       :       11
randaug_n       :       1
kd_lambda       :       1