learner         :       OCM
optim           :       AdamW
learning_rate   :       0.001
momentum        :       0
weight_decay    :       0
dataset         :       cifar100
n_classes       :       100
n_tasks         :       10
mem_size        :       5000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
tf_type         :       full
training_type   :       inc
seed            :       0
proj_dim        :       128