learner         :       DERPPCCLDC
optim           :       AdamW
learning_rate   :       0.0005
momentum        :       0.9
weight_decay    :       0.0001
dataset         :       cifar10
n_classes       :       10
n_tasks         :       5
mem_size        :       500
mem_batch_size  :       64
batch_size      :       10
nf              :       64
training_type   :       inc
seed            :       0
derpp_alpha     :       0.2
derpp_beta      :       1.0
tf_type         :       partial
randaug_m       :       15
randaug_n       :       3
