learner         :       GSA
optim           :       AdamW
learning_rate   :       0.0005
momentum        :       0
weight_decay    :       0.0001
dataset         :       imagenet100
img_size        :       224
n_classes       :       100
n_tasks         :       10
mem_size        :       5000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
tf_type         :       partial
training_type   :       inc
seed            :       0
